### PR TITLE
C API compliance

### LINKED ISSUE #157: R devel issue
Luke has removed `R_ext/PrtUtil.h` in r-devel, so this is failing for me in CI. Do we need it at all?

See also https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/yaml-00install.html

```
  ✖ Failed to build yaml 2.3.11 (1.9s)
  Error: 
  ! error in pak subprocess
  Caused by error in `stop_task_build(state, worker)`:
  ! Failed to build source package yaml.
  Full installation output:
  * installing *source* package ‘yaml’ ...
  ** this is package ‘yaml’ version ‘2.3.11’
  ** package ‘yaml’ successfully unpacked and MD5 sums checked
  staged installation is only possible with locking
  ** using non-staged installation
  ** libs
  using C compiler: ‘gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0’
  gcc -std=gnu2x -I"/opt/R/devel/lib/R/include" -DNDEBUG -I. -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -Wall -pedantic -c api.c -o api.o
  gcc -std=gnu2x -I"/opt/R/devel/lib/R/include" -DNDEBUG -I. -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -Wall -pedantic -c dumper.c -o dumper.o
  gcc -std=gnu2x -I"/opt/R/devel/lib/R/include" -DNDEBUG -I. -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -Wall -pedantic -c emitter.c -o emitter.o
  gcc -std=gnu2x -I"/opt/R/devel/lib/R/include" -DNDEBUG -I. -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -Wall -pedantic -c implicit.c -o implicit.o
  gcc -std=gnu2x -I"/opt/R/devel/lib/R/include" -DNDEBUG -I. -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -Wall -pedantic -c loader.c -o loader.o
  gcc -std=gnu2x -I"/opt/R/devel/lib/R/include" -DNDEBUG -I. -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -Wall -pedantic -c parser.c -o parser.o
  gcc -std=gnu2x -I"/opt/R/devel/lib/R/include" -DNDEBUG -I. -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -Wall -pedantic -c r_emit.c -o r_emit.o
  In file included from r_emit.c:1:
  r_ext.h:19:10: fatal error: R_ext/PrtUtil.h: No such file or directory
     19 | #include "R_ext/PrtUtil.h"
        |          ^~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #157 

Including `R_ext/PrtUtil.h` was the problem. It does not look to be used.

I also removed explicit usage of `R_ext/Print.h`. I'm not sure if it is actually used, but it is documented as being part of `R.h`, which we already include.

I also removed usage of `Rdefines.h`, which is a very old and unmaintained header that looks a bit suspect to me. I would not be surprised if this became non-API in the future. We were transitively getting `Rinternals.h` through this, which we do need, so I swapped it for that.

`Rdefines.h` is just a bunch of macros for common cases, like `GET_LEVELS()` is `Rf_getAttrib(x, R_LevelsSymbol)`
https://github.com/wch/r-source/blob/ad1aa8cb93fb824f161d1a7ec02ff6325683f5fc/src/include/Rdefines.h#L26-L28

### CODE REVIEW

File: src/r_emit.c [hunk 1]
```diff
@@ -274,7 +274,7 @@ static SEXP Ryaml_yoink(SEXP s_vec, int index)
       break;
     case INTSXP:
       if (factor) {
-        s_levels = GET_LEVELS(s_vec);
+        s_levels = getAttrib(s_vec, R_LevelsSymbol);
```
Comment (DavisVaughan) [inline src/r_emit.c]: Not using the `Rf_` prefix seems to be the style of this package, so I matched that.

**Comment by hadley** [comment]
Would you (+ Claude code) be interested in adding the `Rf_` prefix?
